syntax = "proto3";

package lock;

import "google/protobuf/timestamp.proto";

option go_package = "backend/internal/gen/smartlock";

// --- SERVICES ---

service AIService {
    rpc PredictSeverity(PredictSeverityRequest) returns (PredictSeverityResponse);
    rpc RetrainModel(RetrainModelRequest) returns (RetrainModelResponse);
}

service LockService {
    rpc AuthenticateUser(AuthenticateUserRequest) returns (AuthenticateUserResponse);
    rpc RemoteUnlock(RemoteUnlockRequest) returns (RemoteUnlockResponse);
    
    // NOVO: Para enviar a tal "quantidade de eventos" (Batch)
    rpc SendEventBatch(EventBatch) returns (Empty);

    rpc GetSystemHealth(Empty) returns (GetSystemHealthResponse);
}

// --- MESSAGES ---
message Empty {}

enum Severity {
    SEVERITY_OK_UNSPECIFIED = 0;
    SEVERITY_IRREGULAR = 1;
    SEVERITY_SUSPICIOUS = 2;
    SEVERITY_CRITICAL = 3;
}

message SensorEvent {
    string device_id = 1;
    float vibration_intensity = 2;
    string entry_method = 3; // "nfc", "fingerprint", "web_button"
    bool success = 4;
    google.protobuf.Timestamp timestamp = 5;
}

// ESTA É A MUDANÇA PRINCIPAL pedida pelo professor
message EventBatch {
    string device_id = 1;
    repeated SensorEvent events = 2; // Lista de eventos (quantidade variável)
}

message PredictSeverityRequest {
    repeated SensorEvent events = 1;
}

message PredictSeverityResponse {
    Severity classification = 1;
    float confidence = 2;
    string recommendation = 3; 
}

message AuthenticateUserRequest {
    string device_id = 1;
    string auth_type = 2; 
    string credential_payload = 3; 
}

message AuthenticateUserResponse {
    bool authorized = 1;
    string user_name = 2;
}

message RemoteUnlockRequest {
    string requester_id = 1; 
    string secret_key = 2; 
}

message RemoteUnlockResponse {
    bool success = 1;
    string message = 2;
}

message RetrainModelRequest {
    string dataset_path = 1;
    int32 epochs = 2;
}

message RetrainModelResponse {
    bool success = 1;
    string message = 2;
}

message GetSystemHealthResponse {
    string service_name = 1;
    string status = 2; 
    float cpu_usage = 3; 
    float memory_usage = 4; 
}